paginate: 10                                
author:                                    
  name: 进冬
  email: jdzhan@live.com
  link: http://jindong.io
title: 进冬的博客                           
locals:                                    
  tags: 标签
  about: 关于
active: 技术                                
markdown: redcarpet                       